<?php

namespace AppBundle\Repository;

/**
 * PristrojRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PristrojRepository extends \Doctrine\ORM\EntityRepository
{
}
