# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [ in_memory, db_provider ]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$Ub5sjoBwj.iAmr1OW7hFJ.ub.3u11xo1fW1Tck5Qdmi3CJ3IM1EBS
                        roles: 'ROLE_ADMIN'
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
            logout: true

            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout_on_user_change: true
            access_denied_handler: access_denied_handler

    access_control:
            - { path: ^/registration-form-submission$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/(login|register)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }